name: build action
on: [push, pull_request]
jobs:
  build-cmake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
        build_type: [Debug, Release]
    steps:
      - name: clone
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake catch2 protobuf-compiler libprotobuf-dev libcli11-dev
      - name: build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TARGET=GiantDad -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
          cmake --build build
  tests:
    needs: build-cmake
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
        build_type: [Debug, Release]
    if: ${{ success() }}
    steps:
      - name: clone
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake catch2 protobuf-compiler libprotobuf-dev libcli11-dev
      - name: build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TARGET=GiantDadTests -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
          cmake --build build
      - name: test
        run: |
          ./GiantDadTests
  footjob:
    needs: build-cmake, tests
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: chill-drill
        run: |
          echo Hello foot world

